### ISSUE TITLE
Use file extensions that play nice with editors

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle-builder#11]
I ended up having to just tell Atom to use the Handlebars syntax for all `*.html` files, because there's really no other way to get correct Handlebars syntax highlighting automatically in a Fabricator project. This means that anytime I'm editing HTML and it's _not_ in Fabricator, I can't use keyboard shortcuts to auto-comment stuff. Super irritating!

If the desire is to have the files themselves inform their eventual extension, we could adopt a strategy of chaining them, for example `foobar.html.hbs`.

**Comment by lyzadanger** [comment]
Default parsers will happily use either `.hbs` _or_ `.html` and can be overridden with `options`. I can't quite parse your comments, but if you want the extension to be `.hbs`, I think this is done and dusted. There should be more control overall for extensions and parsing.
