### ISSUE TITLE
The term "material" is weird

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle-builder#15]
I've worked on three Fabricator projects so far and I just _can't_ commit the term "material" to memory. They're patterns to me, they're patterns to clients. This one's nitpicky and therefore low-priority, but still... it bugs me!

I think @erikjung told me once that you can make this anything you want, but it's strange to have the _default_ be so idiosyncratic.

**Comment by erikjung** [comment]
I agree. Making `"patterns"` be the default key name shouldn't be too difficult.

**Comment by lyzadanger** [comment]
Good because this has already happened :D

**Comment by lyzadanger** [comment]
This is done!
