### ISSUE TITLE
Hidden patterns

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle-builder#17]
I would like the ability to hide files from any objects passed to templates for iteration in a consistent way. This could either be part of the filename (`_hidden.file`) or a Frontmatter property. The main thing is being able to include partials but not have them be visible by themselves in the styleguide.

A dumb example (only using the underscore here so I don't have to show the frontmatter contents of every file):

```
└── button/
    ├── _base.hbs      Won't show up in style guide
    ├── primary.hbs    May include {{> "button.base" }}
    └── secondary.hbs  May include {{> "button.base" }}
```

**Comment by lyzadanger** [comment]
At present, patterns can be hidden by adding a `collection.y(a)?ml` or `collection.json` file to the collection (i.e. parent directory) and using the `hidden` property:

```
hidden:
  - base
```

**Comment by tylersticka** [comment]
I'd rather this be defined in the patterns themselves, for the same reasons as stated in #31.

**Comment by lyzadanger** [comment]
Possible in patterns as well.
