### ISSUE TITLE
Allow Markdown in any material field or data file

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle-builder#3]
Currently, only the `notes` field in the front-matter allows Markdown. It would be nice to denote Markdown in any field, for example:

```yaml
foo: | **Markdown** content
```

It would also be nice to have this capability in data files as well:

```json 
{
  "foo": "| **Markdown** content"
}
```

**Comment by tylersticka** [comment]
Should this be handled in the data or in the templates? It seems weird to include a piece of content that Markdown would by default convert to `<strong>Markdown</strong>` and have it trigger Markdown parsing.

Alternatively I could see us including some sort of `{{{markdown "**Hello, world!**"}}}` type of helper.

**Comment by erikjung** [comment]
@tylersticka I'm fine with the template helper solution as well. 

I also considered this: https://github.com/jonathantneal/posthtml-md

...But we aren't currently using PostHTML. Yet.

**Comment by lyzadanger** [comment]
I'm totally down with this suggestion but will mention that this is going to incur some possibly-unexpected side effects, like:

`title: A Tisket, A Tasket`

turning into (potentially) `<p>A Tisket a Tasket</p>`

**Comment by tylersticka** [comment]
I know some Markdown parsers allow you to disable features. I wonder if we could create an argument for the helper that parses sans paragraphs or blocks or something? (Not sure which engine we're using, the feature differs with every one I've used.)

**Comment by lyzadanger** [comment]
Yep. I remember futzing with stuff like that. I shall see what I can do!

**Comment by lyzadanger** [comment]
Digging in to this a bit now. As I had feared/remembered, running `marked` indiscriminately across all fields' values will wrap single-line values in `p` tags. You can [write your own parser for paragraphs](http://stackoverflow.com/questions/27663203/markdown-in-js-without-enclosing-p/29559116#29559116) but there are some self-evident issues with stripping _all_ paragraph tags.

We have a few options:

* Have an options object for denoting which fields should be run through markdown
* Have some sort of simple, reliable pattern we can look for in field values that indicates we should markdown it

Let me know your thoughts. Have been talking to @erikjung a bit about this, too.

**Comment by tylersticka** [comment]
So I just chatted with @saralohr about this, and we had a really hard time thinking of instances where we would _need_ the markdown for parsing simple (single-line) strings. The instances where we think it would come in handy are when we have big blocks of content, like a paragraph or more.

Our expectation of a`{{markdown}}` helper is that it would not be any smarter than a default markdown parser. It seems perfectly acceptable (maybe even preferable given its predictability) that it would wrap a single-line string in `<p>` tags.

**Comment by lyzadanger** [comment]
As of now, there is an option (`markdownFields`) that takes an array of field keys as strings. Default is:

`['notes']`

Can be overridden as you like. I'm happy to add other field keys to the default array, also, if you have any in mind.

Let me know if this suffices for this feature!

**Comment by tylersticka** [comment]
I'm confused. Did we decide against the markdown helper in Handlebars? Why is it necessary to pre-define which fields are markdown?

**Comment by lyzadanger** [comment]
Sorry, I conflated two threads. At one point it was discussed having the feature I mentioned in my previous comment. I completely missed the whole handlebars helper thing (yes, I know, reading comprehension and all that). I'll come back to this in a bit...

**Comment by lyzadanger** [comment]
This is available in two ways from the package (global and per-resource-file in front matter). Handling it with a helper is a job for the main `drizzle` package.
