### ISSUE TITLE
Sanity-Check Plan for Individual-Pattern Rendering

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/drizzle-builder#34]
*NB*: This is a long issue summary!

Hullo! This is a complicated concept, so I'll do my very best to be clear. I want to validate my approach on how individual patterns are rendered: their _contexts_, _partials_ and their integration with `handlebars-layouts` and the associated features (`#embed`, `#extend`, e.g.).

## Patterns as Partials; Parsing Patterns

Each pattern file within the `patterns` directory tree is initially registered as a `partial` on `Handlebars` (during the `prepare` phase of build). This doesn't differ much from `fabricator`, except that the namespacing is complete—instead of supporting two levels total, `drizzle` will support an arbitrary depth. Currently namespacing/IDs for pattern partials are dot-separated and remove leading numbers (this is pulled from fabricator). I haven't fully ironed this out, so I'll abstract it out for now.

It may be worth noting that during the `prepare` phase, `layouts` are also registered as partials, and `handlebars-layouts` initialized, etc.

During the `parse` phase (among other things that happen during the parse phase), data is parsed out of pattern front matter and the `patterns` object (large, hierarchical data object that contains a full snapshot of context) is built.

## Pattern Collections

During `render`, pattern `collections` are organized (a `collection` is, roughly, any `patterns` directory that contains at least one immediate child pattern file) and `pattern collection pages` are constructed. Then a `layout` is rendered for each collection page. Right _this moment_, the layout template used to render pattern pages is:

```handlebars
{{#extend "default"}}
  {{#content "body"}}
    <h2>{{collection.name}}</h2>
    {{#each items}}
      {{@key}}
    {{/each}}
  {{/content}}
{{/extend}}
```

That is, this template `extends` the `default` layout, and passes/defines/whatever the `body` block. Right now this doesn't do too much (though it does work!), but my next step might be to evolve it to:

```handlebars
{{#extend "default"}}
  {{#content "body"}}
    <h2>{{collection.name}}</h2>
    {{#each items}}
      {{#embed id context}}
    {{/each}}
  {{/content}}
{{/extend}}
```

Where `id` is the partial ID for the pattern in question and `context` may be a property where I stuff all render context because the individual `pattern` objects are starting to get a lot of properties and I'm worried about collisions. But anyway, the point is: embed a partial representing that pattern with the correct context.

## Integrating `handlebars-layouts`; extending layouts

Now, echoing what I've already done for `page`s, it might be nice to assert that all `pattern` partials `extend` some relevant `layout`. In the case of `pages`, there is a default page `layout`, which can be overridden in front matter. There is a step during render that will check to see if file/template for the `page` in question already has `extend` in its source, if not, it will wrap it. This is easier to illustrate in an example. The following page source:

```handlebars
---
title: Some Page
foo: bar
---
Blah blah blah blah
```

gets automatically turned into:

```handlebars
---
title: Some Page
foo: bar
---
{{#extend 'page'}}
  {{#content 'body'}}
    Blah blah blah blah
  {{/content}}
{{/extend}}
```

but:

```handlebars
---
title: Some Page
foo: bar
---
{{#extend 'page'}}
  {{#content 'body'}}
    Blah blah blah blah
  {{/content}}
{{/extend}}
```

as source would be left alone and

```handlebars
---
title: Some Page
foo: bar
layout: baz
---
Blah blah blah blah
```

would be converted to

```handlebars
---
title: Some Page
foo: bar
layout: baz
---
{{#extend 'baz'}}
  {{#content 'body'}}
    Blah blah blah blah
  {{/content}}
{{/extend}}
```

## Using the Pages-extend metaphor with Patterns

We could also apply this approach to rendering patterns. That is, a pattern:

```handlebars
---
name: My Special Pattern
notes: Some things you should know
---
This is my pattern.
```

Becomes:

```handlebars
---
name: My Special Pattern
notes: Some things you should know
---
{{#extend 'pattern'}}
  {{#content 'body'}}
    This is my pattern.
  {{/content}}
{{/extend}}
```

and

```handlebars
---
name: My Special Pattern
notes: Some things you should know
layout: pattern-variant
---
This is my pattern.
```

becomes

```handlebars
---
name: My Special Pattern
notes: Some things you should know
layout: pattern-variant
---
{{#extend 'pattern-variant'}}
  {{#content 'body'}}
    This is my pattern.
  {{/content}}
{{/extend}}
```

and

```handlebars
---
name: My Special Pattern
notes: Some things you should know
---
{{#extend 'pattern'}}
  {{#content 'some-other-block'}}
    This is my pattern.
  {{/content}}
{{/extend}}
```

is left alone (as it already has the `#extend` in place for the default `pattern` layout).

## Data and Context

You'd also have plenty of context to work with for a given pattern when the partial is rendered, so you could use that in the various layouts in play to do whatever you want. A typical context object would likely look not too different from the fabricator context for the same, e.g.:

* Top-level of context — Anything set in front matter, `title`, etc.
* `patterns` —  A reference to the global `patterns` data object
* `data` — All parsed data from data files
* `pages` — A reference to the global `pages` data object

This seems mostly fine, though there are enough "special" property names in the top level that I worry about collisions a bit.

## Embed replaces `material`

In this approach, the things you get with `handlebars-layouts` would effectively replace a custom helper for embedding patterns. You could use `#embed` anywhere within drizzle source to stick a pattern somewhere (or stick other layouts/things, of course; this isn't limited to patterns).

The questions this all raises:

* Is this approach, leveraging `handelbars-layouts`, a reasonable one?
* Are we comfortable with depending on `handlebars-layouts` in this way?
* Am I correctly grokking `handlebars-layouts`?

/cc @tylersticka @erikjung @mrgerardorodriguez @saralohr @nicolemors

**Comment by lyzadanger** [comment]
Addendum: As I think through this more, I'm thinking there may be good cause still to have a helper, say, called `pattern`. The reason is context. I'd rather not have to have every single `pattern` object carry around an entire copy of global context. If we replace:

```handlebars
{{#extend "default"}}
  {{#content "body"}}
    <h2>{{collection.name}}</h2>
    {{#each items}}
      {{#embed id context}}
    {{/each}}
  {{/content}}
{{/extend}}
```

with 

```handlebars
{{#extend "default"}}
  {{#content "body"}}
    <h2>{{collection.name}}</h2>
    {{#each items}}
      {{#pattern id @root}}
    {{/each}}
  {{/content}}
{{/extend}}
```

The helper in question (`pattern`) could extend root context with local context (I can look up the pattern object using `id`) at time of render, which is a far more efficient and less bug-prone approach than sticking a copy of the entire root context on every pattern object. The rest stays the same (i.e. `pattern` partials extend layouts, etc.).

**Comment by tylersticka** [comment]
I've read through this twice this morning and I'm having a hard time understanding TBH. So the following gut reactions may be invalid.

Firstly, there are a bunch of things I find difficult to use about our Fabricator-based pattern libraries, but including other patterns (via partials or `handlebars-layouts`) is not one of them. So it's difficult to understand what problem we're solving here.

One thing I like about `handlebars-layouts` is how unobtrusive it feels. If we don't _need_ to extend a partial, we don't have to at all. Including a partial set up to be extended via the normal partial syntax `{{> foo}}` will just render any `{{#block}}` with its default content. It's really elegant. So I'd be sad if we lost that.

**Comment by lyzadanger** [comment]
OK! Here's what I think I might do for now, to make progress, until we can get @erikjung 's thoughts:

* It sounds like there might not be a need to _force_ pattern partials to `extend` anything. It _does_ make sense for `pages` I think (I can argue that point if needed, but I'll leave it as an unsupported assertion for now). We can treat pattern partials like, you know, partials.
* BUT we do need to account for `context` when rendering patterns partials from other places, like pattern collection pages. I think for now I'd argue for the `pattern` helper for rendering a partial with the correct context. This will take care of making sure that pattern-specific metadata (`title`, `notes`, etc.) are at the "top level" of the `context` as the partial expects them to be. That is, to account for _local_ context (different per pattern) versus _global_ context (shared by all templates).

I'll try to keep any implementation lightweight should it be _wrong_ :D

**Comment by erikjung** [comment]
This all makes sense to me, and I don't feel like I have any changes to suggest or concerns to raise.

I was wondering about one thing though:

> Am I correctly grokking handlebars-layouts?

Did you try using `{{#embed}}` in place of `{{#extend}}` for the inferred Markdown file layouts?

It's been a few months since I've used these helpers (so naturally I forgot everything), but it seems like this could also work:

```hbs
---
title: Some Page
foo: bar
---
Blah blah blah blah
```

gets automatically turned into:

```hbs
---
title: Some Page
foo: bar
---
{{#embed 'page'}}
  {{#content 'body'}}
    Blah blah blah blah
  {{/content}}
{{/embed}}
```

The front matter is specifying (or defaulting to) an existing layout, so is there any need to `extend` that into a new one? Also, _how_ is it that the source for these helpers is so small? https://github.com/shannonmoeller/handlebars-layouts/blob/master/index.js
