### ISSUE TITLE
Patterns are output in an unexpected dist location

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle-builder#65]
Given these options:

```js
src: {
  patterns: {
    basedir: 'src/patterns',
    glob: 'src/patterns/**/*.hbs'
  },
},
dest: {
  patterns: './dist/patterns'
}
```

The files are being output to:

```
dist/patterns/src/patterns
```

I assume the expected location to be:

```
dist/patterns
```

**Comment by lyzadanger** [comment]
Based on some initial futzing @erikjung and I have tried, this looks like it is something to do with environment differences between executing the `drizzle` function from a `gulp` environment versus `npm` from within the module itself. More to come...inconvenient that I can't reproduce this in the module (those same settings output patterns to the correct, expected destination).

**Comment by lyzadanger** [comment]
I take it back. I forgot that tests use a completely separate configuration (`options` object), which gives them absolute paths for `src` `globs`. I'll look into a way to get absolute paths earlier on and see if I can rectify this...

**Comment by lyzadanger** [comment]
Closer. As of #66 this is working correctly _if_ you use `./` with relative paths (but if you leave out the `./` one extra level of directory gets created). More stable for now; will get this more deeply rooted out soonish.
