### ISSUE TITLE
Misc questions thread

### ISSUE THREAD

**Issue by erikjung** [cloudfour/drizzle-builder#67]
@lyzadanger I'm just going to post things here based on what I encounter during implementation.

**Comment by erikjung** [comment]
### Question:

Given a folder structure like this:

```
src/patterns
├── button
│   ├── base.hbs
│   ├── disabled.hbs
│   └── primary.hbs
└── typography
    ├── headings.hbs
    └── lists.hbs
```

Is there a way to use a `collection.yaml` file to control the ordering of these pattern collections? (e.g. `typography` precedes `button`)

**Comment by erikjung** [comment]
### Question:

Given a folder structure like this:

```
src/pages
├── demos
│   ├── example1.hbs
│   └── example2.hbs
└── index.hbs
```

Is there a way to have corresponding individual pages generated for each file? Currently, the output is structured as one file (`example1.html`) that contains the contents of both source `.hbs` files:

```
dist/demos
└── example1.html
```

**Comment by lyzadanger** [comment]
> Question 2:

Bah! That's what I was trying to suss out in numerous earlier issues. This request is in conflict with what was discussed [in this thread](https://github.com/cloudfour/drizzle-builder/issues/14#issuecomment-194049113) in which it sounded pretty strongly like the desire was _not_ to have individual pages created for patterns :).

**Comment by erikjung** [comment]
> Bah! That's what I was trying to suss out in numerous earlier issues. This request is in conflict with what was discussed in this thread in which it sounded pretty strongly like the desire was not to have individual pages created for patterns :).

I will try a few more things and get back to this...I may just need an additional directory or two inside of `pages`.

**Comment by lyzadanger** [comment]
Oh, wait, _pages_? I'm so sorry. There _should_ be a 1:1 relationship between input pages and output. If you're not seeing this, something is up :). It's possible there is a bug with top-level pages (though there are fixtures...hrm). I'll totally take a look at this tomorrow!

**Comment by erikjung** [comment]
Re: Question 2

To document this further...

I tried adding some nested page folders, and got the following:

**Input:**
```
src/pages
├── demos
│   ├── demo-example-1.hbs
│   ├── demo-example-2.hbs
│   └── index.md
├── docs
│   ├── doc-example-1.md
│   ├── doc-example-2.md
│   └── index.md
└── index.hbs
```

**Output:**
```
dist
├── demo-example-2.html
├── demos
│   └── demo-example-1.html
├── doc-example-2.html
├── docs
│   └── doc-example-1.html
└── index.html
```

Oddly, the nesting gets altered. Also worth noting is that pages with the same base name (for example, `demos/example.hbs` and `docs/example.md`) would collide at the top level. Making each page name unique fixed this.

**Comment by erikjung** [comment]
Re: Question 2

This issue seems to exist for patterns as well, due to similar code in the `walkCollections` function:
https://github.com/cloudfour/drizzle-builder/blob/feature-rewrite/src/write/collections.js#L26-L29

**Comment by erikjung** [comment]
Re: Question 2

Things are now working as expected, thanks to recent commits by @lyzadanger on #68.
