### ISSUE TITLE
Content blocks cannot be extended for pages

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle-builder#81]
Given a hypothetical `test.hbs` layout that extends `blank.hbs`:

```
{{#extend "blank"}}
  {{#content "body" mode="append"}}
    world
  {{/content}}
{{/extend}}
```

And a `test.hbs` page that contains the following:

```
---
title: Test
layout: test
---

Hello
```

I would expect the page output to contain `Hello world`. Instead, it is simply `Hello`.

This is not limited ~~to the "body" block or~~ any particular `mode`. ~~It's as if everything within `{{#content}}` attributes is ignored for extended page layouts.~~

**Comment by mrgerardorodriguez** [comment]
I'm gonna see if I can figure this out. 😬

**Comment by tylersticka** [comment]
Updated description. I originally thought I _also_ couldn't append to `head`, but that wasn't the case... it was just stripping out invalid stuff.

**Comment by tylersticka** [comment]
@mrgerardorodriguez I think I just figured out what the deal is, and it's not a builder issue... it's a front-end issue.

Going to close this and open a new issue on the correct repo.
