### ISSUE TITLE
Test failure: "should ouput pages to the correct output paths"

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle-builder#97]
```
1) write/pages deeply nested pages should ouput pages to the correct output paths:
     AssertionError: expected 'test/dist/pagesnested/demos/demo-example-2.html' to include 'demos/demo-example-2.<!DOCTYPE html>'
      at Context.it (test/write/pages.js:139:31)
```

**Comment by erikjung** [comment]
@tylersticka This test smells a bit.

> AssertionError: expected 'test/dist/pagesnested/demos/demo-example-2.html' to include 'demos/demo-example-2.<!DOCTYPE html>'

That assertion makes no sense to me.

**Comment by gerardo-rodriguez** [comment]
> demos/demo-example-2.<!DOCTYPE html>

Is that supposed to be `demos/demo-example-2.html`?

**Comment by erikjung** [comment]
@gerardo-rodriguez I would assume so.

**Comment by erikjung** [comment]
@gerardo-rodriguez This ain't lookin' right: https://github.com/cloudfour/drizzle-builder/blob/master/test/write/pages.js#L137-L138

I think the `&&` operator here might be a mishap. It looks like `expectedPath` would either evaluate to `false` or to the statement following the `&&`.

**Comment by gerardo-rodriguez** [comment]
@erikjung Oh, good catch. Yeah, that doesn't seem right.

**Comment by gerardo-rodriguez** [comment]
> It looks like `expectedPath` would either evaluate to `false` or to the statement following the `
`&&`.

Yes, I think you are right @erikjung.

**Comment by erikjung** [comment]
Sigh. 

Hiding in plain sight.

https://github.com/cloudfour/drizzle-builder/blob/master/test/fixtures/morePages/demos/demo-example-2.hbs#L2

**Comment by erikjung** [comment]
Resolved via https://github.com/cloudfour/drizzle-builder/issues/100
